# Generated by Django 3.2.15 on 2022-09-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=100)),
                ('body', models.TextField(blank=True, default=0, max_length=1000, null=True)),
                ('icon', models.ImageField(default='images/services-icon.png', upload_to='images/')),
                ('image', models.ImageField(default=0, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='m', max_length=100)),
                ('image', models.ImageField(default=0, upload_to='images/')),
                ('price', models.IntegerField(default=0)),
                ('Product', models.ManyToManyField(to='services.Service')),
            ],
        ),
    ]
