# Generated by Django 4.1.1 on 2022-09-23 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='service',
            name='products',
        ),
    ]
