# Generated by Django 3.2.15 on 2022-09-20 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='test',
        ),
    ]
