# Generated by Django 4.1.1 on 2022-11-10 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesproduct',
            name='image',
        ),
    ]
