# Generated by Django 4.1.1 on 2022-09-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='ServicesProducts',
        ),
    ]
