# Generated by Django 3.2.15 on 2022-09-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='service',
            name='products',
        ),
    ]
