# Generated by Django 4.1.1 on 2022-09-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='services',
            field=models.ManyToManyField(to='services.service'),
        ),
    ]
