# Generated by Django 4.1.1 on 2022-09-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_products_servicesproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesproducts',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
