# Generated by Django 4.1.1 on 2022-09-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicesproducts_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.DeleteModel(
            name='ServicesProducts',
        ),
    ]
