# Generated by Django 4.1.1 on 2022-09-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_services_servicesproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesproducts',
            name='title',
            field=models.CharField(default='m', max_length=100),
        ),
    ]
