# Generated by Django 4.1.1 on 2022-09-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicesproducts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesproducts',
            name='image',
            field=models.ImageField(default=0, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='servicesproducts',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
