# Generated by Django 4.1.1 on 2022-09-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_service_price_remove_service_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesProducts',
            new_name='Products',
        ),
    ]
