# Generated by Django 4.1.1 on 2022-09-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_servicesproducts_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='ServicesProducts',
        ),
    ]
