# Generated by Django 4.1.1 on 2022-11-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=100)),
                ('image', models.ImageField(default=0, upload_to='images/')),
                ('prices', models.TextField(default=0, max_length=1000)),
            ],
        ),
    ]
